StudentCourse.destroy_all
Student.destroy_all
Course.destroy_all
Teacher.destroy_all

student01 = Student.create(first_name: "Tired", last_name: "Todd")
student02 = Student.create(first_name: "Dining", last_name: "Doug")
student03 = Student.create(first_name: "Running", last_name: "Rachel")
student04 = Student.create(first_name: "Jumping", last_name: "Jerod")
student05 = Student.create(first_name: "Mischevious", last_name: "Miwha")
student06 = Student.create(first_name: "Banana", last_name: "Brad")
student07 = Student.create(first_name: "Long-Legs", last_name: "Lilly")
student08 = Student.create(first_name: "Albatross", last_name: "AJ")
student09 = Student.create(first_name: "Elegant", last_name: "Evan")
student10 = Student.create(first_name: "Jolly", last_name: "Jeremy")
student11 = Student.create(first_name: "Zesty", last_name: "Zack")
student12 = Student.create(first_name: "Jazzy", last_name: "Jorge")
student13 = Student.create(first_name: "Alice", last_name: "in Wonderland")
student14 = Student.create(first_name: "Air-Tight", last_name: "Aaron")
student15 = Student.create(first_name: "Mysterious", last_name: "Mike")
student16 = Student.create(first_name: "Dangerous", last_name: "Dillon")
student17 = Student.create(first_name: "Coffee", last_name: "Corey")
student18 = Student.create(first_name: "Arching", last_name: "Adam")
student19 = Student.create(first_name: "Zig-Zag", last_name: "Zack")

teacher1 = Teacher.create(first_name:"Killer", last_name: "Kyle")
teacher2 = Teacher.create(first_name:"Dapper", last_name: "Damon")
teacher3 = Teacher.create(first_name:"Kicking", last_name: "Kat")
teacher4 = Teacher.create(first_name:"Alakazam", last_name: "Ahmed")
teacher5 = Teacher.create(first_name:"Jousting", last_name: "Jesse")
teacher6 = Teacher.create(first_name:"Just", last_name: "Jared")
teacher7 = Teacher.create(first_name:"Sneeky", last_name: "Stephanie")

course1 = Course.create(name: "Enumerables",date_time: "2020-01-01T11:00:00-07:00",teacher_id: teacher1.id)
course2 = Course.create(name: "Apps",date_time: "2020-01-02T11:00:00-07:00",teacher_id: teacher1.id)
course3 = Course.create(name: "Active Record",date_time: "2020-01-11T11:00:00-07:00",teacher_id: teacher2.id)
course4 = Course.create(name: "Hashketball",date_time: "2020-02-01T11:00:00-07:00",teacher_id: teacher2.id)
course5 = Course.create(name: "Bachelor",date_time: "2020-02-01T11:00:00-07:00",teacher_id: teacher3.id)
course6 = Course.create(name: "Python",date_time: "2020-02-02T11:00:00-07:00",teacher_id: teacher4.id)
course7 = Course.create(name: "LinkedIn",date_time: "2020-01-17T11:00:00-07:00",teacher_id: teacher5.id)
course8 = Course.create(name: "Github",date_time: "2020-01-29T11:00:00-07:00",teacher_id: teacher6.id)
course9 = Course.create(name: "Study Hall",date_time: "2020-01-07T11:00:00-07:00",teacher_id: teacher7.id)

student_course01 = StudentCourse.create(student_id: student01.id, course_id: course1.id, status: "Complete")
student_course01 = StudentCourse.create(student_id: student18.id, course_id: course3.id, status: "Incomplete")
student_course01 = StudentCourse.create(student_id: student11.id, course_id: course2.id, status: "Complete")
student_course01 = StudentCourse.create(student_id: student05.id, course_id: course7.id, status: "Incomplete")
student_course01 = StudentCourse.create(student_id: student07.id, course_id: course7.id, status: "Complete")
student_course01 = StudentCourse.create(student_id: student13.id, course_id: course6.id, status: "Incomplete")
student_course01 = StudentCourse.create(student_id: student11.id, course_id: course9.id, status: "Complete")
student_course01 = StudentCourse.create(student_id: student17.id, course_id: course4.id, status: "Incomplete")